#!/bin/bash

# WebM Conversion Utility by MrChowderClam v0.0.1
# Based on the awesome windos version of WebM Conversion Script v0.3.1 by Skyfireblaze & Skyllz

WIDTH=640
QUALITY=4
BITRATE=5
AUDIO="-an"
CODEC="libvpx"

for FILE_NAME
do
	# if it's a gif
	if [[ $FILE_NAME == *gif ]]
		echo -e "Converting $FILE_NAME..."
		/usr/local/bin/ffmpeg -y -i "$FILE_NAME" -c:v $CODEC -crf $QUALITY -b:v ${BITRATE}M "${FILE_NAME}.converted.webm"
	else # if it's not a gif (assume video...)
		echo -e "Converting $FILE_NAME..."
		/usr/local/bin/ffmpeg -y -i "$FILE_NAME" -c:v $CODEC -crf $QUALITY -b:v ${BITRATE}M -vf scale=${WIDTH}:-1 $AUDIO "${FILE_NAME}.converted.webm"
	fi
done

# Finished!
echo -e "Finished Converting $# files."